#!/bin/bash

if [ "$DEPLOYMENT_GROUP_NAME" == "Staging" ]
then
    cd /home/ec2-user
    mkdir Staging
    cd Staging
    echo "This was staging" > staging.txt
elif [ "$DEPLOYMENT_GROUP_NAME" == "CrossRegion-MP" ]
then
    cd /home/ec2-user
    mkdir CrossRegion-MP
    cd CrossRegion-MP
    echo "This CrossRegion-MP" > crossregion.txt
fi